[project]
name = "ai-exam-assistance-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "setuptools==78.1.0",
    "accelerate==1.6.0",
    "acres==0.5.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.11.14",
    "aiosignal==1.3.2",
    "alembic==1.15.2",
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "async-timeout==5.0.1",
    "asyncpg==0.30.0",
    "attrs==25.3.0",
    "bcrypt==4.3.0",
    "blinker==1.9.0",
    "cachetools==5.5.2",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "ci-info==0.3.0",
    "click==8.1.8",
    "configobj==5.0.9",
    "configparser==7.2.0",
    "cryptography==44.0.2",
    "dataclasses-json==0.6.7",
    "decorator==4.4.2",
    "Deprecated==1.2.18",
    "distro==1.9.0",
    "dnspython==2.7.0",
    "ecdsa==0.19.1",
    "email_validator==2.2.0",
    "etelemetry==0.3.1",
    "eval_type_backport==0.2.2",
    "faiss-cpu==1.10.0",
    "fastapi>=0.117.1",
    "fastapi-cli==0.0.7",
    "fastapi-limiter==0.1.6",
    "ffmpeg-python==0.2.0",
    "filelock==3.18.0",
    "Flask==3.1.0",
    "frozenlist==1.5.0",
    "fsspec==2025.3.2",
    "future==1.0.0",
    "git-filter-repo==2.47.0",
    "google-ai-generativelanguage==0.6.15",
    "google-api-core==2.24.2",
    "google-api-python-client==2.166.0",
    "google-auth==2.38.0",
    "google-auth-httplib2==0.2.0",
    "google-generativeai==0.8.4",
    "googleapis-common-protos==1.69.2",
    "greenlet==3.1.1",
    "grpcio==1.71.0",
    "grpcio-status==1.71.0",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httplib2==0.22.0",
    "httptools==0.6.4",
    "httpx==0.28.1",
    "httpx-sse==0.4.0",
    "huggingface-hub==0.30.1",
    "idna==3.10",
    "imageio==2.37.0",
    "imageio-ffmpeg==0.6.0",
    "inquirerpy==0.3.4",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.6",
    "jiter==0.9.0",
    "joblib==1.4.2",
    "jsonpatch==1.33",
    "jsonpointer==3.0.0",
    "langchain==0.3.21",
    "langchain-community==0.3.20",
    "langchain-core==0.3.49",
    "langchain-text-splitters==0.3.7",
    "langsmith==0.3.19",
    "limits==5.2.0",
    "looseversion==1.3.0",
    "lxml==5.4.0",
    "Mako==1.3.9",
    "markdown-it-py==3.0.0",
    "MarkupSafe==3.0.2",
    "marshmallow==3.26.1",
    "mdurl==0.1.2",
    "mistralai==1.6.0",
    "moviepy==1.0.3",
    "mpmath==1.3.0",
    "multidict==6.2.0",
    "mypy-extensions==1.0.0",
    "networkx==3.4.2",
    "nibabel==5.3.2",
    "nipype==1.10.0",
    "numpy==2.2.4",
    "openai==1.70.0",
    "orjson==3.10.16",
    "packaging==24.2",
    "pandas==2.3.0",
    "passlib==1.7.4",
    "pathlib==1.0.1",
    "pdf2image==1.17.0",
    "pdfminer.six==20250327",
    "pdfplumber==0.11.6",
    "pfzy==0.3.4",
    "pgvector==0.4.0",
    "pillow==10.4.0",
    "proglog==0.1.10",
    "prompt_toolkit==3.0.50",
    "propcache==0.3.1",
    "proto-plus==1.26.1",
    "protobuf==5.29.4",
    "prov==2.0.2",
    "psutil==7.0.0",
    "psycopg2==2.9.10",
    "psycopg2-binary==2.9.10",
    "puremagic==1.29",
    "pyasn1==0.4.8",
    "pyasn1_modules==0.4.1",
    "pycparser==2.22",
    "pydantic==2.10.6",
    "pydantic-extra-types==2.10.3",
    "pydantic-settings==2.8.1",
    "pydantic_core==2.27.2",
    "pydot==4.0.0",
    "Pygments==2.19.1",
    "PyJWT==2.10.1",
    "pyparsing==3.2.3",
    "pypdfium2==4.30.1",
    "pytesseract==0.3.13",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "python-http-client==3.3.7",
    "python-jose==3.4.0",
    "python-multipart==0.0.20",
    "pytz==2025.2",
    "pyxnat==1.6.3",
    "PyYAML==6.0.2",
    "razorpay==2.0.0",
    "rdflib==7.1.4",
    "redis==5.2.1",
    "regex==2024.11.6",
    "requests==2.32.3",
    "requests-toolbelt==1.0.0",
    "rich==13.9.4",
    "rich-toolkit==0.14.1",
    "rsa==4.9",
    "safetensors==0.5.3",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "sendgrid==6.11.0",
    "sentence-transformers==4.0.1",
    "sentencepiece==0.2.0",
    "shellingham==1.5.4",
    "simplejson==3.20.1",
    "six==1.17.0",
    "slowapi==0.1.9",
    "sniffio==1.3.1",
    "SQLAlchemy==2.0.40",
    "starkbank-ecdsa==2.2.0",
    "starlette==0.46.1",
    "sympy==1.13.1",
    "tenacity==9.0.0",
    "threadpoolctl==3.6.0",
    "tokenizers==0.21.1",
    "torch==2.6.0",
    "tqdm==4.67.1",
    "traits==7.0.2",
    "transformers==4.51.0",
    "typer==0.15.2",
    "typing-inspect==0.9.0",
    "typing-inspection==0.4.0",
    "typing_extensions==4.13.0",
    "tzdata==2025.2",
    "ujson==5.10.0",
    "uritemplate==4.1.1",
    "urllib3==2.3.0",
    "uvicorn==0.34.0",
    "watchfiles==1.0.4",
    "wcwidth==0.2.13",
    "websockets==15.0.1",
    "Werkzeug==3.1.3",
    "wrapt==1.17.2",
    "yarl==1.18.3",
    "zstandard==0.23.0"
]

