"""Added sub_type column in usersubs

Revision ID: 114b2e3cd4c8
Revises: 8bdd73aa030e
Create Date: 2025-08-27 20:03:32.722915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114b2e3cd4c8'
down_revision: Union[str, None] = '8bdd73aa030e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('subscription_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'subscription_type')
    # ### end Alembic commands ###
