"""Changes in Usersubscription

Revision ID: 29d41c5ff7e4
Revises: 57e8a166bd4e
Create Date: 2025-10-28 19:17:29.293353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d41c5ff7e4'
down_revision: Union[str, None] = '57e8a166bd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('razorpay_plan_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('next_billing_date', sa.DateTime(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('payment_status', sa.String(), nullable=True))
    op.drop_column('user_subscriptions', 'razorpay_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('razorpay_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_subscriptions', 'payment_status')
    op.drop_column('user_subscriptions', 'next_billing_date')
    op.drop_column('user_subscriptions', 'razorpay_plan_id')
    op.drop_column('user_subscriptions', 'razorpay_subscription_id')
    # ### end Alembic commands ###
