"""Updated session_id column in notes and flashcards table

Revision ID: 3316b7fc5b6f
Revises: 578ea87716b5
Create Date: 2025-06-27 15:24:15.916691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3316b7fc5b6f'
down_revision: Union[str, None] = '578ea87716b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('flashcards_session_id_fkey', 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'studysessions', ['session_id'], ['id'])
    op.alter_column('notes', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('notes_session_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'studysessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_session_id_fkey', 'notes', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notes', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key('flashcards_session_id_fkey', 'flashcards', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('flashcards', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
