"""Added last_credit_update

Revision ID: 57e8a166bd4e
Revises: f4a8de95e736
Create Date: 2025-10-19 15:38:09.951477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e8a166bd4e'
down_revision: Union[str, None] = 'f4a8de95e736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('daily_credit_refill', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('max_credits', sa.Integer(), nullable=True))
    op.drop_column('plans', 'monthly_credits')
    op.add_column('users', sa.Column('last_credit_update', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_credit_update')
    op.add_column('plans', sa.Column('monthly_credits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('plans', 'max_credits')
    op.drop_column('plans', 'daily_credit_refill')
    # ### end Alembic commands ###
