"""add is_verified column

Revision ID: 5a48ab077155
Revises: caf581b00471
Create Date: 2025-10-17 19:13:53.494525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a48ab077155'
down_revision: Union[str, None] = 'caf581b00471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verfication_token', sa.Text(), nullable=True))
    op.alter_column('users', 'reset_password_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'reset_password_expiry',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'verfication_token')
    # ### end Alembic commands ###
