"""Updated table QuizQuestion

Revision ID: 735b0afcf791
Revises: 57d5c8ea4b3d
Create Date: 2025-06-28 22:04:35.558161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735b0afcf791'
down_revision: Union[str, None] = '57d5c8ea4b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('type', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('correct_option', sa.String(), nullable=True))
    op.alter_column('quizzes', 'correct_answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'correct_answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('quizzes', 'correct_option')
    op.drop_column('quizzes', 'type')
    # ### end Alembic commands ###
