"""Added billing column in plan

Revision ID: 8bdd73aa030e
Revises: 17b301ebe437
Create Date: 2025-08-27 18:41:57.891361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdd73aa030e'
down_revision: Union[str, None] = '17b301ebe437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('billing_cycle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'billing_cycle')
    # ### end Alembic commands ###
