"""Updated column in QuizQuestion

Revision ID: 9799d912f05a
Revises: 735b0afcf791
Create Date: 2025-06-29 10:19:36.141286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9799d912f05a'
down_revision: Union[str, None] = '735b0afcf791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
