"""Deleting unabled fixes

Revision ID: 9f6e617d19b9
Revises: a939e579d79f
Create Date: 2025-10-06 19:53:35.004368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6e617d19b9'
down_revision: Union[str, None] = 'a939e579d79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flashcards_session_id_fkey', 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'studysessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notes_session_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'studysessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quizzes_session_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'studysessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_session_id_fkey', 'quizzes', 'studysessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_session_id_fkey', 'notes', 'studysessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key('flashcards_session_id_fkey', 'flashcards', 'studysessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
