"""Fixed Typo

Revision ID: b37519da39dd
Revises: 5a48ab077155
Create Date: 2025-10-17 19:21:50.733807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37519da39dd'
down_revision: Union[str, None] = '5a48ab077155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.Text(), nullable=True))
    op.drop_column('users', 'verfication_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verfication_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
