"""add unique constraint to quiz_attempts

Revision ID: b57e8b120283
Revises: 89fd1b1cf889
Create Date: 2025-07-13 14:35:15.569821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57e8b120283'
down_revision: Union[str, None] = '89fd1b1cf889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_question_attempt', 'quiz_attempts', ['user_id', 'question_id', 'attempt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_question_attempt', 'quiz_attempts', type_='unique')
    # ### end Alembic commands ###
