"""Added shared settings

Revision ID: b6cb49899804
Revises: 688292ed2958
Create Date: 2025-11-08 16:43:07.897861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cb49899804'
down_revision: Union[str, None] = '688292ed2958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('share_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'sessions', ['share_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'is_shared')
    op.drop_column('sessions', 'share_id')
    # ### end Alembic commands ###
