"""Changes in Usersubscription Table order_id

Revision ID: c3d835016770
Revises: 29d41c5ff7e4
Create Date: 2025-10-29 20:14:52.858906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d835016770'
down_revision: Union[str, None] = '29d41c5ff7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'razorpay_order_id')
    # ### end Alembic commands ###
