"""did not save 

Revision ID: caf581b00471
Revises: e9f2ade201cf
Create Date: 2025-10-06 20:13:17.417027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf581b00471'
down_revision: Union[str, None] = 'e9f2ade201cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_attempts_user_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.drop_constraint('quiz_attempts_question_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.drop_constraint('quiz_attempts_session_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'studysessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key('quiz_attempts_session_id_fkey', 'quiz_attempts', 'studysessions', ['session_id'], ['id'])
    op.create_foreign_key('quiz_attempts_question_id_fkey', 'quiz_attempts', 'quizzes', ['question_id'], ['id'])
    op.create_foreign_key('quiz_attempts_user_id_fkey', 'quiz_attempts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
