"""Made changes for deleting fc and quizzes

Revision ID: d261e0f3dafb
Revises: 114b2e3cd4c8
Create Date: 2025-10-06 19:43:18.125660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd261e0f3dafb'
down_revision: Union[str, None] = '114b2e3cd4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plans_name_billing_cycle_unique', 'plans', type_='unique')
    op.create_unique_constraint(None, 'plans', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='unique')
    op.create_unique_constraint('plans_name_billing_cycle_unique', 'plans', ['name', 'billing_cycle'])
    # ### end Alembic commands ###
