"""Add attempt_number to quiz_attempts

Revision ID: d51651d3016b
Revises: da2019cc1705
Create Date: 2025-07-13 09:23:40.562580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51651d3016b'
down_revision: Union[str, None] = 'da2019cc1705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('attempt_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'attempt_number')
    # ### end Alembic commands ###
