"""add credits to user and monthly_credits

Revision ID: f4a8de95e736
Revises: c9ee42bbee18
Create Date: 2025-10-19 14:39:44.163222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a8de95e736'
down_revision: Union[str, None] = 'c9ee42bbee18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('monthly_credits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    op.drop_column('plans', 'monthly_credits')
    # ### end Alembic commands ###
